---
title: "Rail Trail t Test"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---

```{r, message=FALSE, warning=FALSE}
#library(mosaic)
library(DT)
library(pander)
```

<!-- Instructions

1. Use the RailTrail dataset in R to come up with a question that can be answered with a t Test. 

2. Establish why the question is interesting and rephrase the question using a statistical "null" and "alternative" hypothesis. (Hint, see the "Math 325 Notebook -> R Help -> R-Markdown Hints" page of your textbook for instructions on how to write mathematical hypotheses.)

3. Clearly answer your question using statistics. Be sure to compute a p-value and provide supporting numerical and graphical summaries.

For details about the RailTrail dataset type the command:
  > ?RailTrail 
into your Console and study the help file that appears. Also, if you want extra information, browse this document that has images and further details:
http://www.northamptonma.gov/DocumentCenter/View/5244   


Note: you can create "groups" from the data in many ways. For example, you can create a variable in your RailTrail dataset that is called "rain" and has categories of "yes" and "no" with the code:



-->

```{r}
#library(ggplot2)
#library(mosaic)
library(reshape2)
library(plotly)
#library(pander)


# Add new columns for Weekday and Weekend in the style as the season columns
railtrail <- read.csv("../Data/railtrail.csv")

# Step 1
cormat_trail <- round(cor(railtrail),2)
head(cormat_trail)

# Step 2
melted_cormat <- melt(cormat_trail)
head(melted_cormat)

# Step 3
get_upper_tri <- function(data_set){
  data_set[lower.tri(data_set)] <- NA
  return(data_set)
}

upper_tri_trai <- get_upper_tri(cormat_trail)
melted_upper_tri <- melt(upper_tri_trai, na.rm = TRUE)
head(melted_upper_tri)

# Step 4
ggplot(data = melted_upper_tri, aes(Var2, Var1, fill = value)) +
  geom_tile(color = "white") + 
  geom_text(aes(label = value), color = "black") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0, limit = c(-1, 1), space = "lab",
                       name = "Pearson\nCorrelation") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.justification = c(1, 0),
        legend.position = c(0.40, 0.75),
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                               title.position = "top", title.hjust = 0.5)) +
  coord_fixed() +
  labs(
    title = ""
  )

rail.scale <- as.data.frame(scale(railtrail))
View(rail.scale)

# Layered Density Plot of High Temperature and Volume of Visitors
plot_1 <- ggplot() +
  geom_density(data = rail.scale,
                 aes(x = hightemp),
               fill = "red",
               alpha = 0.25) +
  geom_density(data = rail.scale,
                 aes(x = volume),
               fill = "blue",
               alpha = 0.25) +
  theme_bw()

# Faceted Density Plot
plot_2 <- ggplot() +
  geom_density(data = rail.scale,
               aes(x = hightemp),
               fill = "red",
               alpha = 0.25) +
  theme_bw()

plot_3 <- ggplot() +
  geom_density(data = rail.scale,
               aes(x = volume),
               fill = "blue",
               alpha = 0.25) +
  theme_bw()

# Adjust layout of the graphs
grid <- matrix(c(1, 1, 2, 3),
               nrow = 2,
               ncol = 2,
               byrow = TRUE)

```

