---
title: "Analysis 1 - Stephanie"
author: "Daniel Lopez"
date: "September 20, 2018"
output: 
  html_document:
    theme: paper
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)
library(leaflet)
library(USAboundaries)

Rent <- read_csv("../../Data/Rent.csv") %>% 
  na.omit()
```



```{r, fig.align='center', comment=NA, warning=FALSE}
### Distance ~ Price ~ Gender
CheapNClose <- 
  Rent %>% 
  filter(Price < quantile(Rent$Price, 0.30)) %>% 
  filter(MilesToCampus < quantile(Rent$MilesToCampus, 0.30))


Rent %>% 
  ggplot(aes(MilesToCampus, Price, color = Gender, group = Gender)) +
  geom_point() +
  geom_label_repel(data = CheapNClose, aes(label = Apartment),
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50',
                   alpha = 0.7) +
  geom_smooth(se = FALSE) +
  facet_grid(Gender ~ .) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90), legend.position = "none") +
  labs(
    x = "Miles to Campus",
    y = "Price",
    color = "Gender"
  )

```



```{r, fig.align='center'}
### Leaflet Map
getColor <- function(Rent) {
  sapply(Rent$Price, function(Price) {
    if(Price <= 1000) {
      "green"
    } else if(Price <= 1200) {
      "yellow"
    } else {
      "red"
    } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(Rent)
)

leaflet(options = leafletOptions()) %>% 
  addTiles() %>% 
  addLabelOnlyMarkers(data = CheapNClose,
             label = ~Apartment,
             labelOptions = labelOptions(noHide = T)) %>%
  addAwesomeMarkers(data = Rent,
                    lng = ~Longitude,
                    lat = ~Latitude,
                    icon = icons,
                    popup = ~paste0("Name: ", Apartment, "<br/>",
                                    "Gender: ", Gender, "<br/>",
                                    "Address: ", Address, "<br/>",
                                    "Phone: ", Phone, "<br/>",
                                    "Shared Room: ", Price, "<br/>",
                                    "Private Room: ", PrivateRoomPrice, "<br/>",
                                    "Deposit: ", Deposit, "<br/>"))
```

